/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Task;
import classes.TaskTree;
import enums.Priority;
import interfaces.TaskCallback;
import java.util.Date;
import javax.swing.JComboBox;
import manipulations.DateVerification;
import manipulations.DateTimeConverter;

/**
 *
 * @author theobenvie-watson
 */
public class AddTask extends javax.swing.JFrame {

    String title;
    String description;
    Date dueDay;
    Priority selectedPriority;
    private TaskCallback callback;

    public AddTask(TaskCallback callback) {
        initComponents();
        this.callback = callback;
    }

    public AddTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slashMonthLabel = new javax.swing.JLabel();
        colonLabel = new javax.swing.JLabel();
        PriorityLabel = new javax.swing.JLabel();
        addTaskButton = new javax.swing.JButton();
        PrioritySelection = new javax.swing.JComboBox<>(Priority.values());
        slashDayLabel = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        minuteText = new javax.swing.JTextField();
        hourText = new javax.swing.JTextField();
        titleText = new javax.swing.JTextField();
        dayText = new javax.swing.JTextField();
        monthText = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        backgroundPNG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 420));
        setPreferredSize(new java.awt.Dimension(747, 423));
        setSize(new java.awt.Dimension(747, 423));
        getContentPane().setLayout(null);

        slashMonthLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        slashMonthLabel.setForeground(new java.awt.Color(102, 102, 102));
        slashMonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slashMonthLabel.setText("/");
        getContentPane().add(slashMonthLabel);
        slashMonthLabel.setBounds(637, 100, 20, 20);

        colonLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        colonLabel.setForeground(new java.awt.Color(102, 102, 102));
        colonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colonLabel.setText(":");
        getContentPane().add(colonLabel);
        colonLabel.setBounds(430, 100, 20, 20);

        PriorityLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        PriorityLabel.setForeground(new java.awt.Color(255, 255, 255));
        PriorityLabel.setText("Priority:");
        getContentPane().add(PriorityLabel);
        PriorityLabel.setBounds(530, 170, 110, 20);

        addTaskButton.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        addTaskButton.setForeground(new java.awt.Color(255, 255, 255));
        addTaskButton.setText("Add New Task +");
        addTaskButton.setContentAreaFilled(false);
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addTaskButton);
        addTaskButton.setBounds(20, 330, 710, 50);

        PrioritySelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioritySelectionActionPerformed(evt);
            }
        });
        getContentPane().add(PrioritySelection);
        PrioritySelection.setBounds(530, 210, 190, 40);

        slashDayLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        slashDayLabel.setForeground(new java.awt.Color(102, 102, 102));
        slashDayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slashDayLabel.setText("/");
        getContentPane().add(slashDayLabel);
        slashDayLabel.setBounds(572, 100, 20, 20);

        descriptionText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        descriptionText.setText("placeholder description");
        descriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextActionPerformed(evt);
            }
        });
        getContentPane().add(descriptionText);
        descriptionText.setBounds(28, 211, 460, 80);

        yearText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        yearText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearText.setText("2002");
        yearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextActionPerformed(evt);
            }
        });
        getContentPane().add(yearText);
        yearText.setBounds(660, 92, 60, 40);

        minuteText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        minuteText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minuteText.setText("45");
        minuteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuteTextActionPerformed(evt);
            }
        });
        getContentPane().add(minuteText);
        minuteText.setBounds(450, 92, 50, 40);

        hourText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        hourText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hourText.setText("10");
        hourText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourTextActionPerformed(evt);
            }
        });
        getContentPane().add(hourText);
        hourText.setBounds(380, 92, 50, 40);

        titleText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        titleText.setText("placeholder title");
        titleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextActionPerformed(evt);
            }
        });
        getContentPane().add(titleText);
        titleText.setBounds(28, 92, 320, 40);

        dayText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        dayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayText.setText("26");
        dayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextActionPerformed(evt);
            }
        });
        getContentPane().add(dayText);
        dayText.setBounds(530, 92, 40, 40);

        monthText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        monthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthText.setText("09");
        monthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextActionPerformed(evt);
            }
        });
        getContentPane().add(monthText);
        monthText.setBounds(595, 92, 40, 40);

        descriptionLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Description:");
        getContentPane().add(descriptionLabel);
        descriptionLabel.setBounds(30, 170, 140, 20);

        dateLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date:");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(535, 60, 140, 20);

        timeLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("Time:");
        getContentPane().add(timeLabel);
        timeLabel.setBounds(390, 60, 110, 20);

        titleLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Title:");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(30, 60, 140, 20);

        MainTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(167, 202, 177));
        MainTitle.setText("Add a Task >");
        getContentPane().add(MainTitle);
        MainTitle.setBounds(10, 0, 270, 40);

        backgroundPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/addTask.png"))); // NOI18N
        backgroundPNG.setText("jLabel1");
        getContentPane().add(backgroundPNG);
        backgroundPNG.setBounds(0, -10, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minuteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minuteTextActionPerformed

    private void titleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextActionPerformed

    private void hourTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourTextActionPerformed

    private void yearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextActionPerformed

    private void dayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextActionPerformed

    private void monthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextActionPerformed

    private void descriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextActionPerformed

    
    private void PrioritySelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioritySelectionActionPerformed
        this.selectedPriority = (Priority) PrioritySelection.getSelectedItem();
    }//GEN-LAST:event_PrioritySelectionActionPerformed

    
    public void setVariables(){
        this.title = titleText.getText();
        this.description = descriptionText.getText();
        Date set = DateTimeConverter.stringToDate(dayText.getText() + "/" +
                monthText.getText() + "/" + yearText.getText() + " " +
                hourText.getText() + ":" +
                minuteText.getText());
        this.dueDay = set;
    }
    
    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

        if (checkInputs().isEmpty()) {
            setVariables();
            Task toAdd = new Task(this.title, this.dueDay);
            toAdd.setPriority(selectedPriority);
            toAdd.setDescription(description);
            callback.onTaskCreated(toAdd);
            dispose();
        }
        
        AddError window = new AddError();
        window.show();
        clearTextFields();
    } 
    
    public void clearTextFields() {
        minuteText.setText("");
        titleText.setText("");
        hourText.setText("");
        yearText.setText("");
        dayText.setText("");
        monthText.setText("");
        descriptionText.setText("");
    }

    public String checkInputs() {
        String errors = "";

        if (minuteText.getText().isEmpty()) {
            errors += "Minute field is empty.\n";
        }
        if (titleText.getText().isEmpty()) {
            errors += "Title field is empty.\n";
        }
        if (hourText.getText().isEmpty()) {
            errors += "Hour field is empty.\n";
        }
        if (yearText.getText().isEmpty()) {
            errors += "Year field is empty.\n";
        }
        if (dayText.getText().isEmpty()) {
            errors += "Day field is empty.\n";
        }
        if (monthText.getText().isEmpty()) {
            errors += "Month field is empty.\n";
        }
        if (descriptionText.getText().isEmpty()) {
            errors += "Description field is empty.\n";
        }

        int hour = Integer.parseInt(hourText.getText());
        int minute = Integer.parseInt(minuteText.getText());
        int year = Integer.parseInt(yearText.getText());
        int month = Integer.parseInt(monthText.getText());
        int day = Integer.parseInt(dayText.getText());

        DateVerification dateVerification = new DateVerification(hour, minute, year, month, day);
        String dateErrors = dateVerification.validate();
        if (!dateErrors.isEmpty()) {
            errors += dateErrors;
        }

        return errors;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel PriorityLabel;
    private javax.swing.JComboBox<Priority> PrioritySelection;
    private javax.swing.JButton addTaskButton;
    private javax.swing.JLabel backgroundPNG;
    private javax.swing.JLabel colonLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dayText;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JTextField hourText;
    private javax.swing.JTextField minuteText;
    private javax.swing.JTextField monthText;
    private javax.swing.JLabel slashDayLabel;
    private javax.swing.JLabel slashMonthLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleText;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
