/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author theobenvie-watson
 */
public class AddTask extends javax.swing.JFrame {

    /**
     * Creates new form AddTask
     */
    public AddTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upNext1 = new javax.swing.JLabel();
        upNext5 = new javax.swing.JLabel();
        upNext6 = new javax.swing.JLabel();
        upNext7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        upNext4 = new javax.swing.JLabel();
        upNext3 = new javax.swing.JLabel();
        upNext2 = new javax.swing.JLabel();
        upNext = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 420));
        setPreferredSize(new java.awt.Dimension(747, 423));
        setSize(new java.awt.Dimension(747, 423));
        getContentPane().setLayout(null);

        upNext1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext1.setForeground(new java.awt.Color(255, 255, 255));
        upNext1.setText("Add New Task +");
        getContentPane().add(upNext1);
        upNext1.setBounds(290, 340, 160, 30);

        upNext5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext5.setForeground(new java.awt.Color(102, 102, 102));
        upNext5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upNext5.setText("/");
        getContentPane().add(upNext5);
        upNext5.setBounds(637, 100, 20, 20);

        upNext6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext6.setForeground(new java.awt.Color(102, 102, 102));
        upNext6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upNext6.setText(":");
        getContentPane().add(upNext6);
        upNext6.setBounds(430, 100, 20, 20);

        upNext7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext7.setForeground(new java.awt.Color(102, 102, 102));
        upNext7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upNext7.setText("/");
        getContentPane().add(upNext7);
        upNext7.setBounds(572, 100, 20, 20);

        jTextField7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextField7.setText("placeholder description");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(28, 211, 690, 80);

        jTextField4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("2002");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(660, 92, 60, 40);

        jTextField1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("45");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 92, 50, 40);

        jTextField3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("10");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 92, 50, 40);

        jTextField2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextField2.setText("placeholder title");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(28, 92, 320, 40);

        jTextField5.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("26");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(530, 92, 40, 40);

        jTextField6.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("09");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(595, 92, 40, 40);

        upNext4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext4.setForeground(new java.awt.Color(255, 255, 255));
        upNext4.setText("Description:");
        getContentPane().add(upNext4);
        upNext4.setBounds(30, 170, 140, 20);

        upNext3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext3.setForeground(new java.awt.Color(255, 255, 255));
        upNext3.setText("Date:");
        getContentPane().add(upNext3);
        upNext3.setBounds(535, 60, 140, 20);

        upNext2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext2.setForeground(new java.awt.Color(255, 255, 255));
        upNext2.setText("Time:");
        getContentPane().add(upNext2);
        upNext2.setBounds(390, 60, 110, 20);

        upNext.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        upNext.setForeground(new java.awt.Color(255, 255, 255));
        upNext.setText("Title:");
        getContentPane().add(upNext);
        upNext.setBounds(30, 60, 140, 20);

        MainTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(167, 202, 177));
        MainTitle.setText("Add a Task >");
        getContentPane().add(MainTitle);
        MainTitle.setBounds(10, 0, 270, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/taskAdd.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel upNext;
    private javax.swing.JLabel upNext1;
    private javax.swing.JLabel upNext2;
    private javax.swing.JLabel upNext3;
    private javax.swing.JLabel upNext4;
    private javax.swing.JLabel upNext5;
    private javax.swing.JLabel upNext6;
    private javax.swing.JLabel upNext7;
    // End of variables declaration//GEN-END:variables
}
