/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author theobenvie-watson
 */
public class AddTask extends javax.swing.JFrame {

    /**
     * Creates new form AddTask
     */
    public AddTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmButton = new javax.swing.JLabel();
        dashDate = new javax.swing.JLabel();
        semiTime = new javax.swing.JLabel();
        dashDay = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        minutesText = new javax.swing.JTextField();
        hourText = new javax.swing.JTextField();
        titleText = new javax.swing.JTextField();
        dayText = new javax.swing.JTextField();
        monthText = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        backgroundPNG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 420));
        setPreferredSize(new java.awt.Dimension(747, 423));
        setSize(new java.awt.Dimension(747, 423));
        getContentPane().setLayout(null);

        confirmButton.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Add New Task +");
        getContentPane().add(confirmButton);
        confirmButton.setBounds(290, 340, 160, 30);

        dashDate.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        dashDate.setForeground(new java.awt.Color(102, 102, 102));
        dashDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashDate.setText("/");
        getContentPane().add(dashDate);
        dashDate.setBounds(637, 100, 20, 20);

        semiTime.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        semiTime.setForeground(new java.awt.Color(102, 102, 102));
        semiTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semiTime.setText(":");
        getContentPane().add(semiTime);
        semiTime.setBounds(430, 100, 20, 20);

        dashDay.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        dashDay.setForeground(new java.awt.Color(102, 102, 102));
        dashDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashDay.setText("/");
        getContentPane().add(dashDay);
        dashDay.setBounds(572, 100, 20, 20);

        descriptionText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        descriptionText.setText("placeholder description");
        descriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextActionPerformed(evt);
            }
        });
        getContentPane().add(descriptionText);
        descriptionText.setBounds(28, 211, 690, 80);

        yearText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        yearText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearText.setText("2002");
        yearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextActionPerformed(evt);
            }
        });
        getContentPane().add(yearText);
        yearText.setBounds(660, 92, 60, 40);

        minutesText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        minutesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minutesText.setText("45");
        minutesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesTextActionPerformed(evt);
            }
        });
        getContentPane().add(minutesText);
        minutesText.setBounds(450, 92, 50, 40);

        hourText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        hourText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hourText.setText("10");
        hourText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourTextActionPerformed(evt);
            }
        });
        getContentPane().add(hourText);
        hourText.setBounds(380, 92, 50, 40);

        titleText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        titleText.setText("placeholder title");
        titleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextActionPerformed(evt);
            }
        });
        getContentPane().add(titleText);
        titleText.setBounds(28, 92, 320, 40);

        dayText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        dayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayText.setText("26");
        dayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextActionPerformed(evt);
            }
        });
        getContentPane().add(dayText);
        dayText.setBounds(530, 92, 40, 40);

        monthText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        monthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthText.setText("09");
        monthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextActionPerformed(evt);
            }
        });
        getContentPane().add(monthText);
        monthText.setBounds(595, 92, 40, 40);

        descriptionLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Description:");
        getContentPane().add(descriptionLabel);
        descriptionLabel.setBounds(30, 170, 140, 20);

        dateLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date:");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(535, 60, 140, 20);

        timeLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("Time:");
        getContentPane().add(timeLabel);
        timeLabel.setBounds(390, 60, 110, 20);

        titleLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Title:");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(30, 60, 140, 20);

        MainTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(167, 202, 177));
        MainTitle.setText("Add a Task >");
        getContentPane().add(MainTitle);
        MainTitle.setBounds(10, 0, 270, 40);

        backgroundPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/taskAdd.png"))); // NOI18N
        backgroundPNG.setText("jLabel1");
        getContentPane().add(backgroundPNG);
        backgroundPNG.setBounds(0, -10, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minutesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutesTextActionPerformed

    private void titleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextActionPerformed

    private void hourTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourTextActionPerformed

    private void yearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextActionPerformed

    private void dayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextActionPerformed

    private void monthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextActionPerformed

    private void descriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel backgroundPNG;
    private javax.swing.JLabel confirmButton;
    private javax.swing.JLabel dashDate;
    private javax.swing.JLabel dashDay;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dayText;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JTextField hourText;
    private javax.swing.JTextField minutesText;
    private javax.swing.JTextField monthText;
    private javax.swing.JLabel semiTime;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleText;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
