package gui;

/**
 *
 * @author theobenvie-watson
 */
public class Name extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Name() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continueButton = new javax.swing.JButton();
        nameError = new javax.swing.JLabel();
        frameTitle = new javax.swing.JLabel();
        versionNo = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        namePrompt = new javax.swing.JLabel();
        nameSubmission = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TaskTree");
        setForeground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(514, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(514, 350));
        getContentPane().setLayout(null);

        continueButton.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText("Continue");
        continueButton.setContentAreaFilled(false);
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(continueButton);
        continueButton.setBounds(140, 270, 230, 30);

        nameError.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        nameError.setForeground(new java.awt.Color(153, 0, 0));
        nameError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nameError);
        nameError.setBounds(112, 230, 290, 30);

        frameTitle.setBackground(new java.awt.Color(255, 255, 255));
        frameTitle.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        frameTitle.setForeground(new java.awt.Color(255, 255, 255));
        frameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameTitle.setText("TaskTree");
        getContentPane().add(frameTitle);
        frameTitle.setBounds(0, 0, 190, 30);

        versionNo.setForeground(new java.awt.Color(255, 255, 255));
        versionNo.setText("v1.0");
        getContentPane().add(versionNo);
        versionNo.setBounds(0, 330, 30, 17);

        welcomeText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Welcome!");
        getContentPane().add(welcomeText);
        welcomeText.setBounds(60, 50, 250, 30);

        namePrompt.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        namePrompt.setForeground(new java.awt.Color(255, 255, 255));
        namePrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namePrompt.setText("What is your name?");
        getContentPane().add(namePrompt);
        namePrompt.setBounds(140, 120, 230, 30);

        nameSubmission.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        nameSubmission.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameSubmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSubmissionActionPerformed(evt);
            }
        });
        getContentPane().add(nameSubmission);
        nameSubmission.setBounds(110, 170, 290, 50);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Untitled (1).png"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 514, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameSubmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSubmissionActionPerformed

    }//GEN-LAST:event_nameSubmissionActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed

        if (!nameSubmission.getText().isEmpty()) {
            Home mainScreen = new Home(nameSubmission.getText());
            mainScreen.show();
            dispose();
        } else if (nameSubmission.getText().isEmpty()){
            nameError.setVisible(true);
            nameError.setText("Please enter your name.");
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Name().setVisible(true);
                new Name().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel frameTitle;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel namePrompt;
    private javax.swing.JTextField nameSubmission;
    private javax.swing.JLabel versionNo;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
